"""
mailer.py — Sends extracted insights via Gmail SMTP.
"""
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from config import EMAIL_SENDER, EMAIL_PASSWORD, EMAIL_TO
from mock_mode import email_configured


def send_email(extracted: dict) -> dict:
    if not email_configured():
        return {
            "success": False,
            "message": "Email not configured. Add EMAIL_SENDER, EMAIL_PASSWORD, EMAIL_TO in config.py."
        }
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"AI Smart-Distiller Report — {datetime.now().strftime('%b %d, %Y %H:%M')}"
        msg["From"]    = EMAIL_SENDER
        msg["To"]      = EMAIL_TO

        tasks_html = "".join(
            f"<li style='margin:6px 0;'>{t}</li>" for t in extracted.get("tasks", [])
        ) or "<li>No tasks found.</li>"

        deadlines_html = "".join(
            f"<li style='margin:6px 0;'><strong>{d['date']}</strong> — {d['context']}</li>"
            for d in extracted.get("deadlines", [])
        ) or "<li>No deadlines found.</li>"

        html = f"""
        <html><body style="font-family:Georgia,serif;max-width:620px;margin:auto;color:#1a1a2e;">
          <div style="background:#0f0f23;padding:24px 32px;border-radius:8px 8px 0 0;">
            <h1 style="color:#e8d5b7;margin:0;font-size:22px;">AI Smart-Distiller</h1>
            <p style="color:#a0a0c0;margin:4px 0 0;font-size:13px;">Automated Insight Report</p>
          </div>
          <div style="background:#fafaf8;padding:24px 32px;border:1px solid #e0ddd5;border-top:none;border-radius:0 0 8px 8px;">
            <h2 style="font-size:16px;color:#333;border-bottom:2px solid #e8d5b7;padding-bottom:8px;">Summary</h2>
            <p style="line-height:1.7;color:#444;">{extracted.get("summary","N/A")}</p>
            <h2 style="font-size:16px;color:#333;border-bottom:2px solid #c8e6c9;padding-bottom:8px;margin-top:24px;">Action Items</h2>
            <ul style="line-height:1.7;color:#444;">{tasks_html}</ul>
            <h2 style="font-size:16px;color:#333;border-bottom:2px solid #fff3cd;padding-bottom:8px;margin-top:24px;">Deadlines</h2>
            <ul style="line-height:1.7;color:#444;">{deadlines_html}</ul>
            <p style="font-size:11px;color:#999;margin-top:32px;border-top:1px solid #eee;padding-top:12px;">
              Generated by AI Smart-Distiller · FAST-NUCES · {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}
            </p>
          </div>
        </body></html>
        """
        msg.attach(MIMEText(html, "html"))

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(EMAIL_SENDER, EMAIL_PASSWORD)
            server.sendmail(EMAIL_SENDER, EMAIL_TO, msg.as_string())

        return {"success": True, "message": f"Email sent to {EMAIL_TO} successfully."}
    except Exception as e:
        return {"success": False, "message": f"Email error: {str(e)}"}
